<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSOYFKC6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSOYFKC6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSOYFKC6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSOYFKC6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSOYFKC6\App_KernelDevDebugContainer([
    'container.build_hash' => 'SOYFKC6',
    'container.build_id' => '139e3f40',
    'container.build_time' => 1629129932,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSOYFKC6');
